server:
  port: 9596
spring:


  datasource:
    url: jdbc:mysql://server3.leemaster.cn:3306/flowers?useSSL=false
    username: flowers
    password: Flowers666
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: you-money-categories-service
eureka:
  client:
    service-url:
      defaultZone: http://server2.leemaster.cn:8761/youmoney,http://server1.leemaster.cn:8761/youmoney
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}




